
version: '2'
services:
  web:
    restart: always
    build: 
        context: ./web
        dockerfile: Dockerfile.txt
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn -b :8000 app:app

  nginx:
    restart: always
    build: 
        context: ./nginx
        dockerfile: Dockerfile.txt
    ports:
      - "80:80"
    links:
      - "web"